add "Open Rule link in browser"
checkstyle/eclipse-cs pull request #267
Opened 2020-09-13 03:05 UTC by qxo

This PR will index the checks.html content, link rule to the detail url.
ie:
```
AbstractClassName -->  https://checkstyle.sourceforge.io/config_naming.html#AbstractClassName
```

we can change the rule info url：
```
-Declipsecs_rules_url=https://checkstyle.sourceforge.io/checks.html
```

2020-09-14 14:46 UTC, romani requested changes
please fix CI.

item:

2020-09-14 14:46 UTC, romani commented on net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/stats/views/RuleLinkHelper.java
> +          "https://checkstyle.sourceforge.io/checks.html");
should be changed to `checkstyle.org` it is primary domain.

2020-09-14 19:59 UTC, romani commented
CI failures https://travis-ci.org/github/checkstyle/eclipse-cs/jobs/727087072#L962 please fix

2020-09-19 14:09 UTC, romani commented
@qxo ,
you will not need to cache anything ones https://github.com/checkstyle/eclipse-cs/pull/257 is merged.
Please help to test this PR, it will simplify a lot your PR and any other problems.

2020-09-19 15:05 UTC, qxo commented
> @qxo ,
> you will not need to cache anything ones #257 is merged.
> Please help to test this PR, it will simplify a lot your PR and any other problems.

ok, if I had the time.

What's the #257 problem which we should focus on?

2020-09-19 15:43 UTC, romani commented
> What's the #257 problem which we should focus on?

we try to get all data about Checks from checkstyle library itself as checkstyle jar now contain almost all metadata(all docs) that is required for plugin and users.

2023-09-19 17:30 UTC, Bananeweizen commented
I'd like to close this in favour of #568. I'd avoid trying to index any online URL to get the available help URLs.
We could eventually resurrect the "Open URL" actions from this PR.

2023-09-19 17:30 UTC, closed without merging